# Site settings
title: Varian Style Guide
description: A repository of common UI patterns and for the Oncology 360 client.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
source: docs
destination: build/docs
sass:
  sass_dir: _styles
kramdown:
  syntax_highlighter: rouge

nav:
- title: Layout
- title: Content
  pages:
  - title: Typography
  - title: Colors
  - title: Utilities
- title: Components
  pages:
    - title: Widget
    - title: Card
    - title: Table
    - title: Forms
    - title: ChartView

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"